### ISSUE TITLE
White screen when opening/loading the app

### ISSUE THREAD

**Issue by matuella** [olmps/memo#130]
**Descreva o Bug/Describe the bug:**

There is a white page before displaying the `SplashPage`. If the white page takes too long (usually during the first application's initialization), the `SplashPage` doesn't even appear.

Possibly only iOS physical device, have to check if Android physical devices also have the same problem.

Have to check if the same occurs on emulators.

**Passos para Reproduzir/Steps to Reproduce:**

1. Open the app.

**Resultado Esperado/Expected Result:**

Always displaying the `SplashPage` until the application is fully loaded.

**Resultado Obtido/Actual Result:**

White page appears before the `SplashPage`.

**Versão do app/App Version:**

0.1.0, iOS 14.6 iPhone 6s

**Comment by ggirotto** [comment]
In physical Android the SplashScreen is working as expected
