### ISSUE TITLE
Link do Discord Expirou

### ISSUE THREAD

**Issue by IgorVini25** [olmps/memo#133]
**Descrição do Bug:**

Ao ir nas configurações (menu no canto superior direito) e ir na opção "Discord", o aplicativo redireciona o usuário, porém ao ir para o discord o discord avisa que o link foi expirado

**Passos Reproduzidos:**

1. Abra o app
2. Entre no menu no canto superior direito
3. Clique na opção "Discord"

**Resultado Esperado:**

Redirecionar o usuário ao discord com uma tela de convite ao suposto servidor.

**Resultado Obtido:**

Tela de "convite expirou"

**Screenshots:**

https://user-images.githubusercontent.com/71888091/126051986-89c81478-2462-46ed-9dbb-6ff2f3f68b2b.mp4

**Versão do app:**

Versão 0.1.0

**Comment by ludovicobesana** [comment]
I confirm that the bug is still present 🐛

**Comment by matuella** [comment]
Subi um PR fixando o link do discord para um link permanente sem limite de usos, muito obrigado pelas contribuições @ludovicobesana @IgorVini25
