### ISSUE TITLE
Sobreposição dos emojis sobre o conteúdo nas respostas

### ISSUE THREAD

**Issue by aphenrique** [olmps/memo#151]
**Descreva o Bug/Describe the bug:**

Ao acessar as respostas dos "memos", no conteúdo de flutter, os emojis ficaram sobrepostos à resposta, impedindo que fossem lidas.
Possívelmente, um widget rolável resolveria o problema.
Acontece em android e iOS
Testei em aparelhos antigos e com telas menores, mas qualquer conteúdo maior poderia trazer a questão à tona mesmo em aparelhos mais novos e telas maiores

<-- Faça uma clara e breve descrição do problema / Provide us a brief and clear description of the problem -->

**Passos para Reproduzir/Steps to Reproduce:**

<-- Quais os passos necessários para que o bug seja reproduzido? / What are the necessary steps to reproduce this bug?
Exemplo/Example:

Abra o app, escolha a coleção de flutter e perceba o problema nas respostas com textos grandes.

**Resultado Esperado/Expected Result:**

Algum tipo de scroll para telas menores.

**Resultado Obtido/Actual Result:**

<-- Qual resultado você obteve? / What happened instead? -->

**Screenshots:**

<-- Se possível, adicione Screenshots para ilustrar o problema. / If applicable, adds some Screenshots to illustrate 
the problem. -->

**Versão do app/App Version:**
Tenho um Moto G3 para testes aqui e foi onde instalei. Tetei no iphone 5s e também acontece.

<-- Versão do app na qual o problema foi reproduzido / App version in use when the problem was reproduced -->

**Comment by matuella** [comment]
Muito obrigado pelo report do bug @aphenrique !

De fato, é definitivamente um comportamento não esperado. Vou tentar reproduzir aqui no local com os devices mencionados e atualizo essa issue assim que possível.
