### ISSUE TITLE
Questões mais claras e objetivas

### ISSUE THREAD

**Issue by Victor-BwD** [olmps/memo#152]
Achei um comentário no Google Play bem interessante, que é a questão das perguntas.

As perguntas serem mais objetivas ou ter algum texto padrão como "O quer é essa frase abaixo:" ou "O quer quer dizer ... ...." ficaria mais didático e melhor.

Pra mim mesmo apareceu apenas "GIT" ou um código do SHA1 e eu não entendi muito bem o que queria dizer. Saberia se fosse melhor formulado a pergunta.

**Comment by mathmorais** [comment]
Eu notei esse problema também, colocar um texto padrão é uma ótima ideia, mas também pode gerar conflitos dependendo da questão, considerando o exemplo abaixo: 

<img width=200 src="https://user-images.githubusercontent.com/70591271/126221347-b38d2ac2-7c6c-425e-91c3-1c4ed5706a83.png"/>

Poderia ser modificado para "O que o código **$ git config --global core.editor emacs** realiza no seu projeto" ou algo que se encaixasse naquele contexto.

Uma outra ideia também, para seguir a interface no estilo terminal seria de utilizar comentários para descrever melhor as perguntas, por exemplo: 

```bash
## O que o código abaixo realiza no seu projeto
$ git config --global core.editor emacs
```

**Comment by IgorVini25** [comment]
Entrei aqui pra abrir umas Issue sobre isso, e já tinha, não fui só eu que percebi isso então

**Comment by matuella** [comment]
Muito obrigado pelas contribuições pessoal, Concordo com os pontos de vocês, falta contexto para essa coleção.

Quando eu fiz esta coleção, acabei seguindo muito as recomendações de criar flashcards (a inspiração fundamental das coleções/memos) e acredito que acabei por ser muito mais sucinto do que o ideal - ainda mais caso os recursos associados com aquela coleção não tenham sido lidos.

Vou categorizar esta issue como melhoria - agora, especificamente, para melhorar esta coleção de fundamentos do git. Tirando esta coleção (fundamentos do git), vocês acreditam que existam outras que são demasiadamente concisas?

**Comment by mathmorais** [comment]
Obrigado pela resposta @matuella, pelo que eu observei, eu acredito que seja apenas essa coleção em que as perguntas precisam ser reformuladas.

**Comment by matuella** [comment]
Pessoal, subi uma melhoria sobre essa coleção e caso acreditem ainda não estar minimamente coesa, podem abrir essa issue novamente.

Se tiverem outras sugestões para outras coleções, por favor, abram issues (ou se possível pull requests) para tais coleções.

Muito obrigado pela contribuição de todos.

**Comment by Victor-BwD** [comment]
Obrigado pela atualização @matuella, fiquei um tempo fora mas vou voltar a testar o app. Pode contar comigo para mais opiniões.
