### ISSUE TITLE
Setup GithubAction with Flutter

### ISSUE THREAD

**Issue by gustavohd18** [olmps/memo#16]
**Caso de Uso/Use Case:**
If we have GitActions for Flutter set, it would be possible to check Lint, tests, etc in each PR.

**Proposta/Proposal:**
Creation of Gitactions for Flutter.

**Comment by matuella** [comment]
I would also add that when we are uploading to AppStore, ideally it should also be done by the CI (through `fastlane`), and not manually.

Thanks for the suggestion. Even though we aren't planning to pick this improvement for now, it will be a nice enhancement.

**Comment by ggirotto** [comment]
It would be an awesome enhancement to the project. If you have experience with Github Actions and want to contribute with the project, I suggest to open a PR with this feature, would be great to have this integration in the repo.

**Comment by matuella** [comment]
Closed with #18
