### ISSUE TITLE
Chaning the profile picture is not affecting the rank list

### ISSUE THREAD

**Issue by jonata97** [olmps/memo#180]
**Descreva o Bug/Describe the bug:**

<-- Faça uma clara e breve descrição do problema / Provide us a brief and clear description of the problem -->

**Passos para Reproduzir/Steps to Reproduce:**

<-- Quais os passos necessários para que o bug seja reproduzido? / What are the necessary steps to reproduce this bug?
Exemplo/Example:
1. Abra o app/Open the app
2. Entre na tela X/Navigate to X Screen
3. Clique no componente Y/Tap in the component Y -->

**Resultado Esperado/Expected Result:**

<-- Qual resultado você esperava? / What did you expect to achieve? -->

**Resultado Obtido/Actual Result:**

<-- Qual resultado você obteve? / What happened instead? -->

**Screenshots:**

<-- Se possível, adicione Screenshots para ilustrar o problema. / If applicable, adds some Screenshots to illustrate 
the problem. -->

**Versão do app/App Version:**

<-- Versão do app na qual o problema foi reproduzido / App version in use when the problem was reproduced -->

**Comment by ggirotto** [comment]
Maybe we should listen for the public info changes for each user in the rankings list. What do you think @matuella ?
