### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by lizzi2122** [olmps/memo#24]
**Caso de Uso/Use Case:**

<-- Quais casos de uso são impactados por essa nova funcionalidade? Quais problemas ela resolve? / What use cases would 
have a direct impact on this new feature? What problems does it solve? -->

**Proposta/Proposal:**

<-- Faça uma breve porém informativa descrição da sua proposta. Se possível, ilustre ela com imagens / Do a brief and 
complete description of your proposal. If applicable, illustrate it with images. -->

**Comment by ggirotto** [comment]
Please, follow [CONTRIBUTING.md](https://github.com/olmps/memo/blob/main/CONTRIBUTING.md), the issues are not a chat feature
