### ISSUE TITLE
Typo on cards' questions/answers  of "BDD - Fundamentos" Collection 

### ISSUE THREAD

**Issue by revagomes** [olmps/memo#286]
**Descreva o Bug/Describe the bug:**

There are a few occurences of "orientado a comportamente" (with the letter "E") rather than "orientado a comportamento" (with the letter "O") on some cards of the BDD - Fundamentos Collection.

As soon as the set of cards are shown the users will see a few of them having that typo on some of the questions and the answers as well. 

**Passos para Reproduzir/Steps to Reproduce:**

1. Open the app
2. Navigate to Explore Screen
3. Tap in the component BDD - Fundamentos
4. The first card already has the typo previously described 

**Resultado Esperado/Expected Result:**

```
[...]
      "uniqueId": "03c9a8d5-9e27-4ec2-8a3c-7bf20431b823",
      "question": [
        {
          "insert": "Os cenários no desenvolvimento orientado a comportamento (BDD) segue o fomato DADO-QUANDO-ENTÃO, popularlmente conhecido como ___.\n"
        }
      ],
      "answer": [
        {
          "insert": "Os cenários no desenvolvimento orientado a comportamento (BDD) segue o fomato DADO-QUANDO-ENTÃO, popularlmente conhecido como "
        },
[...]
```

**Resultado Obtido/Actual Result:**

```
[...]
      "uniqueId": "03c9a8d5-9e27-4ec2-8a3c-7bf20431b823",
      "question": [
        {
          "insert": "Os cenários no desenvolvimento orientado a comportamente (BDD) segue o fomato DADO-QUANDO-ENTÃO, popularlmente conhecido como ___.\n"
        }
      ],
      "answer": [
        {
          "insert": "Os cenários no desenvolvimento orientado a comportamente (BDD) segue o fomato DADO-QUANDO-ENTÃO, popularlmente conhecido como "
        },
[...]
```

**Versão do app/App Version:**

Latest release - 0.2.0

**Comment by matuella** [comment]
Fixed by #285
