### ISSUE TITLE
Codecov is not working properly

### ISSUE THREAD

**Issue by matuella** [olmps/memo#39]
You can see that in the PRs #35, #36, #37 and #38 , the coverage suggestion is for some reason the same as the #33

**Comment by RaphaelOliveiraMoura** [comment]
@matuella Does this problem keep happening?

**Comment by matuella** [comment]
It appears that this only occurs when multiple PRs are opened simultaneously. I will try to replicate this issue once again, if not, I will close it. Thanks for asking!

**Comment by abelborges** [comment]
FYI https://arstechnica.com/gadgets/2021/04/backdoored-developer-tool-that-stole-credentials-escaped-notice-for-3-months/

**Comment by matuella** [comment]
@abelborges thanks for the info, I have been watching these codecov issues and I think this isn't a reliable tool anymore for us to use with github actions, which could lead to use eventually exposing some private keys (through a supply chain attack).

https://www.theregister.com/2021/05/05/twilio_codecov_attack/ is another good ref.

My take on this is that we should migrate to [coveralls](https://coveralls.io/) or [code climate](https://codeclimate.com/).

**Comment by matuella** [comment]
Given the new updates made to the github actions, I am closing in favor of #84
