### ISSUE TITLE
Erro no link para o README_ptbr

### ISSUE THREAD

**Issue by AugustoSavi** [olmps/memo#5]
Ao clicar no link para o README_ptbr

![image](https://user-images.githubusercontent.com/32443720/112190081-6c8dc700-8be3-11eb-9e09-2a22ae935ecc.png)
![image](https://user-images.githubusercontent.com/32443720/112190181-862f0e80-8be3-11eb-8732-8be9ca9b76ee.png)
![image](https://user-images.githubusercontent.com/32443720/112190203-8a5b2c00-8be3-11eb-97fb-ada0c858ce5d.png)

Só tirar a barra do link para o README_ptbr.md  que já resolve o problema
![image](https://user-images.githubusercontent.com/32443720/112190407-baa2ca80-8be3-11eb-9e23-9fa6dd5e7abb.png)

**Comment by matuella** [comment]
De fato é um link quebrado que foi solucionado com o PR #6.

Muito obrigado pela contribuição @AugustoSavi
