### ISSUE TITLE
Criar cards com parte do código selecionado

### ISSUE THREAD

**Issue by yzk23** [olmps/memo#7]
**Caso de Uso/Use Case:**

Selecionar parte do código para criação do _card_ de forma personalizada. 
Assim seria possível memorizar a parte do código realmente importante e não toda sua estrutura.

**Proposta/Proposal:**

Caso seja feita mais de uma seleção no código, criar a quantidades de _cards_ por seleção.
Por exemplo, o [mem.dev](https://mem.dev) utiliza-se desse recurso.

**Comment by matuella** [comment]
Olá @yzk23, antes de mais nada, muito obrigado pela contribuição.

Não sei se entendi muito bem a sua sugestão, mas a ideia é adicionar uma maneira de editar/criar o seu próprio card e permitir que o próprio usuário consiga inserir/remover/editar esse mesmo código?

Caso seja isso, eu acredito que é de fato uma ótima sugestão, no entanto eu acredito que em primeira instância nós vamos tentar melhorar um pouco mais da experiência da execução do card antes de permitir a criação de cards customizados. 

De qualquer maneira, vou deixar essa issue aqui aberta como ponto de melhoria futura, para quando voltarmos para estas definições de cards customizados.

**Comment by matuella** [comment]
Irei transformar esta issue em uma discussion de Idea, pois acredito ser o melhor lugar até construirmos uma ideia um pouco mais clara de como seria a implementação desta funcionalidade.
