### ISSUE TITLE
Improves Workflows by reusing Composite Actions

### ISSUE THREAD

**Issue by ggirotto** [olmps/memo#80]
Currently, most of the [pull-requers workflow](https://github.com/olmps/memo/pull/78/files/b9e083c30e424829fadf9d3a40707f6d74552807..37f10c90d285494939ade3fe95194e32a471a4a9#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0) is copy-pasted from the [release workflow](https://github.com/olmps/memo/pull/78/files/37f10c90d285494939ade3fe95194e32a471a4a9#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34). Github Actions has "composite actions", which let us reuse the workflow scripts but it currently has a limitations that makes unsustainable to use it as it is today

The main limitation that difficult our workflows today is that the composite actions doesn't support the `use` step, which unable us to reuse most part of the duplicate code between the worflows.

See more: https://github.com/actions/runner/issues/646

**Comment by matuella** [comment]
Closed because #78 doesn't reuse almost anything of the release workflow anymore
