### ISSUE TITLE
Missing safe area for devices with home indicator

### ISSUE THREAD

**Issue by brunosquadros** [olmps/memo#95]
**Describe the bug:**
The app is not using a safe area for devices with a home indicator.

**App Version:**
iPhone Xs 0.1.0 (7)

![IMG_4ACD514CC2F6-1](https://user-images.githubusercontent.com/4096458/118493966-0b243900-b6f8-11eb-9335-447d56da627a.jpeg)

**Comment by matuella** [comment]
Thanks for reporting this out, it's indeed a bug that we will look into it.

**Comment by IshankDev** [comment]
Hey fixed this issue at my end but not able to create the pull request. Please provide the access :)

**Comment by matuella** [comment]
Hey @IshankDev, thanks for helping out on this. For you to merge into this repository, you must fork it, make changes to your fork and the suggest a PR from this fork, [this link](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) may help you out on how to do this.
